// Copyright 2026 Ekumen Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef ROSIDL_TYPESUPPORT_CPYTHON__IDENTIFIER_HPP_
#define ROSIDL_TYPESUPPORT_CPYTHON__IDENTIFIER_HPP_

#include "rosidl_typesupport_cpython/visibility_control.h"

namespace rosidl_typesupport_cpython
{

/// Identifier of this (dispatch) typesupport.
/**
 * Handles generated by this package carry this identifier in their
 * `typesupport_identifier` field, and their `func` is
 * `get_message_typesupport_handle_function` — the dlsym-based dispatcher that
 * resolves a concrete CPython typesupport implementation (e.g.
 * `rosidl_typesupport_xcdr_cpython`) from the per-message
 * `type_support_map_t`.
 */
ROSIDL_TYPESUPPORT_CPYTHON_EXPORT
extern const char * typesupport_identifier;

}  // namespace rosidl_typesupport_cpython

#endif  // ROSIDL_TYPESUPPORT_CPYTHON__IDENTIFIER_HPP_
